export const MOODS = [
  {
    id: "reflective",
    label: "Reflective",
    bg: "bg-slate-900",
    text: "text-slate-200",
    border: "border-slate-700",
    prompt: "I want to think deeply.",
    hexBg: "#0f172a",
    tocBg: "#1e293b",
    epubText: "#e2e8f0",
    scrollbarThumb: "#334155",
    scrollbarTrack: "#0f172a",
  },
  {
    id: "nostalgic",
    label: "Nostalgic",
    bg: "bg-[#f4ecd8]",
    text: "text-amber-950",
    border: "border-amber-200",
    prompt: "I want something comforting.",
    hexBg: "#f4ecd8",
    tocBg: "#eaddc5",
    epubText: "#431407",
    scrollbarThumb: "#dcbda5",
    scrollbarTrack: "#f4ecd8",
  },
  {
    id: "dark",
    label: "Dark",
    bg: "bg-[#1a0b0c]",
    text: "text-[#fecaca]",
    border: "border-[#3f1619]",
    prompt: "I want tension and mystery.",
    hexBg: "#1a0b0c",
    tocBg: "#2d1417",
    epubText: "#fecaca",
    scrollbarThumb: "#7f1d1d",
    scrollbarTrack: "#1a0b0c",
  },
  {
    id: "romantic",
    label: "Romantic",
    bg: "bg-rose-50",
    text: "text-rose-950",
    border: "border-rose-200",
    prompt: "I want to feel dreamy.",
    hexBg: "#fff1f2",
    tocBg: "#ffe4e6",
    epubText: "#4c0519",
    scrollbarThumb: "#fecdd3",
    scrollbarTrack: "#fff1f2",
  },
  {
    id: "escapist",
    label: "Escapist",
    bg: "bg-teal-950",
    text: "text-teal-100",
    border: "border-teal-800",
    prompt: "Take me far away.",
    hexBg: "#042f2e",
    tocBg: "#115e59",
    epubText: "#ccfbf1",
    scrollbarThumb: "#134e4a",
    scrollbarTrack: "#042f2e",
  },
];

export const ERAS = [
  {
    id: "victorian",
    label: "19th Century",
    desc: "Gaslight, grand estates, and classical prose.",
  },
  {
    id: "roaring",
    label: "Early 20th Century",
    desc: "Modernism, societal shifts, and jazz age.",
  },
  {
    id: "ancient",
    label: "Antiquity",
    desc: "Myths, early philosophy, and epics.",
  },
];
