export const DISCOVERY_THOUGHTS = {
  reflective: [
    "What's occupying your mind right now?",
    "If you could pause time for one hour, what would you do?",
    "What is a question you've been avoiding lately?",
    "What feels important to you today, even if you can't explain why?",
    "Is there something small that’s been quietly bothering you?",
    "What kind of version of yourself are you trying to become lately?",
    "When was the last time you felt truly present?",
    "What thought keeps returning, no matter how much you ignore it?",
    "If today had a theme, what would it be?",
    "What’s something you wish you understood better about yourself?",
    "What’s been quietly shaping your thoughts today?",
    "Is there something you’ve been overthinking lately?",
    "What do you wish you could slow down and notice more?",
    "What feels unresolved in your mind right now?",
    "What are you learning about yourself these days?",
    "What thought feels important, even if it's unclear?",
    "What would you tell your past self about this phase of life?",
    "What’s something you’ve been meaning to understand?",
    "What feels different about you compared to last year?",
    "What’s something you’re still figuring out?",
  ],

  nostalgic: [
    "Describe a moment from your past that feels like a warm hug.",
    "What is a smell or sound that instantly transports you back in time?",
    "If you could revisit one day in your life, which would it be and why?",
    "What’s a memory that still makes you smile without trying?",
    "Who do you miss in a quiet, unspoken way?",
    "What was life like when things felt simpler?",
    "What’s something from your past you didn’t realize you’d cherish later?",
    "If you could relive a small moment, not a big one, what would it be?",
    "What place from your past still feels like home?",
    "What version of you do you sometimes miss?",
    "What’s a moment that still feels vivid no matter how much time passes?",
    "Who made your world feel lighter back then?",
    "What’s something you wish you could experience again for the first time?",
    "What did happiness look like in that memory?",
    "What’s a place you haven’t visited in a long time but think about often?",
    "What’s a simple routine from your past you miss?",
    "What kind of days felt endless in a good way?",
    "What made you feel safe back then?",
    "What memory feels soft around the edges?",
    "What’s something you didn’t realize would become a memory?",
  ],

  dark: [
    "What shadow are you trying to understand today?",
    "Write down a fear you haven't confessed to anyone.",
    "If the night could listen, what would you tell it?",
    "What thought feels too heavy to say out loud?",
    "What part of yourself do you keep hidden from others?",
    "What are you tired of carrying?",
    "Is there something you're afraid might be true?",
    "What does your silence usually hide?",
    "What would you admit if you knew no one would judge you?",
    "What’s been draining you more than it should?",
    "What feeling have you been avoiding lately?",
    "What keeps you up when everything is quiet?",
    "What truth feels uncomfortable to face?",
    "What are you pretending doesn’t matter?",
    "What part of your life feels out of control?",
    "What are you silently struggling with?",
    "What feels heavier than it should?",
    "What are you holding in that needs release?",
    "What thought are you afraid to sit with?",
    "What feels uncertain in a way you can’t explain?",
  ],

  romantic: [
    "What does love feel like to you in this exact moment?",
    "Describe a tiny, seemingly insignificant gesture that means the world to you.",
    "Who is taking up space in your heart today, and why?",
    "What kind of love are you hoping to receive right now?",
    "What’s something that makes you feel deeply seen?",
    "How do you show care when words aren’t enough?",
    "What memory feels soft and close to your heart?",
    "What does comfort look like in a person?",
    "What’s a small moment that felt like everything?",
    "What does being understood feel like to you?",
    "What kind of connection are you craving lately?",
    "What makes you feel gently understood?",
    "What does affection look like in your world?",
    "What’s something that made your heart feel full recently?",
    "What kind of moments feel like love to you?",
    "What does emotional closeness mean to you?",
    "What’s a small act that made you feel valued?",
    "What kind of presence feels comforting to you?",
    "What does warmth in a person look like?",
    "What’s something you wish someone understood about you?",
  ],

  escapist: [
    "If you could step through a portal right now, where would it lead?",
    "What are you running away from, or running towards?",
    "Describe the world you wish you were waking up in tomorrow.",
    "What kind of place feels like an escape for you?",
    "If nothing was holding you back, where would you go first?",
    "What does your perfect quiet day look like somewhere else?",
    "What would you leave behind without hesitation?",
    "What kind of story would you want to live inside for a while?",
    "If you disappeared for a bit, where would you want to be found?",
    "What version of life feels just out of reach right now?",
    "What kind of world would you build for yourself right now?",
    "What feels like a distant place you want to escape to?",
    "If you could pause your life and restart somewhere new, where would it be?",
    "What kind of environment feels like freedom to you?",
    "What would your life look like in a different setting?",
    "What are you quietly hoping to leave behind?",
    "What kind of story would you disappear into for a while?",
    "What version of reality feels easier than this one?",
    "Where does your mind go when it wants to wander?",
    "What kind of place feels like it understands you?",
  ],

  default: [
    "Take a deep breath. How are you really feeling?",
    "What is one word that describes your state of mind right now?",
    "Leave a thought here before you continue your journey.",
    "What’s something small you noticed today?",
    "How would you describe today in a sentence?",
    "What’s on your mind that you haven’t said yet?",
    "What kind of energy are you carrying right now?",
    "Is there something you need, but haven’t asked for?",
    "What would make today feel a little better?",
    "What’s one honest thought you can leave here?",
    "What’s something you haven’t said out loud today?",
    "What’s been sitting in your thoughts quietly?",
    "How does this moment feel, right now?",
    "What’s one thing you’re carrying into the rest of your day?",
    "What feels important, even if it’s small?",
    "What kind of mood are you in, honestly?",
    "What’s something you want to hold onto from today?",
    "What’s something you’d like to let go of?",
    "What’s been on your mind without interruption?",
    "What’s one thought you can leave here before moving on?",
  ],
};

export const READING_THOUGHTS = [
  "What drew you to this specific book today?",
  "Before you begin, what are you hoping to find in these pages?",
  "If this book could answer one question for you, what would it be?",
  "What do you think the author was feeling when they wrote the first page?",
  "Imagine an alternative ending before the story even begins.",
  "Are you looking for an escape, or a reflection of your own reality?",
  "What is the first thing you notice when you enter a new world?",
  "What kind of journey are you about to step into?",
  "Do you think you'll relate to someone in this book?",
  "What would make this reading experience feel worth it?",
  "Take a moment — you're about to enter someone else's world.",
  "What kind of mood are you bringing into this story?",
  "Some stories stay longer than expected. Will this be one of them?",
  "Is this a slow read kind of day, or a page-turner mood?",
  "What’s the first line going to make you feel?",
  "Are you here for comfort, curiosity, or something unexpected?",
  "Every book begins quietly — what will this one become?",
  "Do you think this story will surprise you?",
  "What would you like to take away from this, even in a small way?",
  "Sometimes the right book feels effortless. Let’s see.",
  "Will you remember this story a week from now?",
  "Is this a story you’ll sit with, or fly through?",
  "Let the first few pages decide everything.",
  "Some stories unfold slowly — give this one a moment.",
  "What kind of world are you hoping this becomes?",
];
